# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 919)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_init_data = QtWidgets.QWidget()
        self.tab_init_data.setObjectName("tab_init_data")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_init_data)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox = QtWidgets.QGroupBox(self.tab_init_data)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_15.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_init_data)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_10 = QtWidgets.QLabel(self.groupBox_16)
        self.label_10.setLineWidth(1)
        self.label_10.setObjectName("label_10")
        self.gridLayout_16.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_16.addWidget(self.label_14, 1, 3, 1, 1)
        self.doubleSpinBox_soil_high_level_depth = QtWidgets.QDoubleSpinBox(self.groupBox_16)
        self.doubleSpinBox_soil_high_level_depth.setObjectName("doubleSpinBox_soil_high_level_depth")
        self.gridLayout_16.addWidget(self.doubleSpinBox_soil_high_level_depth, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_16.addWidget(self.label_13, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_16)
        self.label_11.setObjectName("label_11")
        self.gridLayout_16.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_16)
        self.label_15.setObjectName("label_15")
        self.gridLayout_16.addWidget(self.label_15, 2, 0, 1, 1)
        self.spinBox_soil_resistivity_low = QtWidgets.QSpinBox(self.groupBox_16)
        self.spinBox_soil_resistivity_low.setMaximum(10000)
        self.spinBox_soil_resistivity_low.setObjectName("spinBox_soil_resistivity_low")
        self.gridLayout_16.addWidget(self.spinBox_soil_resistivity_low, 2, 2, 1, 1)
        self.label_131 = QtWidgets.QLabel(self.groupBox_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_131.setFont(font)
        self.label_131.setObjectName("label_131")
        self.gridLayout_16.addWidget(self.label_131, 2, 3, 1, 1)
        self.spinBox_soil_resistivity_high = QtWidgets.QSpinBox(self.groupBox_16)
        self.spinBox_soil_resistivity_high.setMaximum(10000)
        self.spinBox_soil_resistivity_high.setObjectName("spinBox_soil_resistivity_high")
        self.gridLayout_16.addWidget(self.spinBox_soil_resistivity_high, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem1, 1, 1, 1, 1)
        self.comboBox_soil_resistivity_high = QtWidgets.QComboBox(self.groupBox_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_soil_resistivity_high.sizePolicy().hasHeightForWidth())
        self.comboBox_soil_resistivity_high.setSizePolicy(sizePolicy)
        self.comboBox_soil_resistivity_high.setObjectName("comboBox_soil_resistivity_high")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.comboBox_soil_resistivity_high.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_soil_resistivity_high, 1, 4, 1, 1)
        self.comboBox_soil_resistivity_low = QtWidgets.QComboBox(self.groupBox_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_soil_resistivity_low.sizePolicy().hasHeightForWidth())
        self.comboBox_soil_resistivity_low.setSizePolicy(sizePolicy)
        self.comboBox_soil_resistivity_low.setObjectName("comboBox_soil_resistivity_low")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.comboBox_soil_resistivity_low.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_soil_resistivity_low, 2, 4, 1, 1)
        self.gridLayout_16.setColumnStretch(0, 7)
        self.gridLayout_16.setColumnStretch(2, 2)
        self.gridLayout_16.setColumnStretch(3, 1)
        self.gridLayout_16.setColumnStretch(4, 3)
        self.verticalLayout_14.addLayout(self.gridLayout_16)
        self.gridLayout_15.addWidget(self.groupBox_16, 2, 0, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_init_data)
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem2, 0, 1, 1, 1)
        self.spinBox_ground_electrode_vertical_diameter = QtWidgets.QSpinBox(self.groupBox_17)
        self.spinBox_ground_electrode_vertical_diameter.setObjectName("spinBox_ground_electrode_vertical_diameter")
        self.gridLayout_18.addWidget(self.spinBox_ground_electrode_vertical_diameter, 2, 2, 1, 1)
        self.comboBox_ground_electrode_vertical_length = QtWidgets.QComboBox(self.groupBox_17)
        self.comboBox_ground_electrode_vertical_length.setObjectName("comboBox_ground_electrode_vertical_length")
        self.comboBox_ground_electrode_vertical_length.addItem("")
        self.comboBox_ground_electrode_vertical_length.addItem("")
        self.comboBox_ground_electrode_vertical_length.addItem("")
        self.comboBox_ground_electrode_vertical_length.addItem("")
        self.comboBox_ground_electrode_vertical_length.addItem("")
        self.comboBox_ground_electrode_vertical_length.addItem("")
        self.comboBox_ground_electrode_vertical_length.addItem("")
        self.comboBox_ground_electrode_vertical_length.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_ground_electrode_vertical_length, 0, 4, 1, 1)
        self.doubleSpinBox_ground_electrode_vertical_length = QtWidgets.QDoubleSpinBox(self.groupBox_17)
        self.doubleSpinBox_ground_electrode_vertical_length.setObjectName("doubleSpinBox_ground_electrode_vertical_length")
        self.gridLayout_18.addWidget(self.doubleSpinBox_ground_electrode_vertical_length, 0, 2, 1, 1)
        self.label_150 = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_150.setFont(font)
        self.label_150.setObjectName("label_150")
        self.gridLayout_18.addWidget(self.label_150, 2, 3, 1, 1)
        self.label_145 = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_145.setFont(font)
        self.label_145.setObjectName("label_145")
        self.gridLayout_18.addWidget(self.label_145, 0, 3, 1, 1)
        self.label_144 = QtWidgets.QLabel(self.groupBox_17)
        self.label_144.setObjectName("label_144")
        self.gridLayout_18.addWidget(self.label_144, 2, 0, 1, 1)
        self.comboBox_ground_electrode_vertical_type = QtWidgets.QComboBox(self.groupBox_17)
        self.comboBox_ground_electrode_vertical_type.setObjectName("comboBox_ground_electrode_vertical_type")
        self.comboBox_ground_electrode_vertical_type.addItem("")
        self.comboBox_ground_electrode_vertical_type.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_ground_electrode_vertical_type, 1, 2, 1, 1)
        self.label_141 = QtWidgets.QLabel(self.groupBox_17)
        self.label_141.setObjectName("label_141")
        self.gridLayout_18.addWidget(self.label_141, 1, 0, 1, 1)
        self.label_143 = QtWidgets.QLabel(self.groupBox_17)
        self.label_143.setObjectName("label_143")
        self.gridLayout_18.addWidget(self.label_143, 0, 0, 1, 1)
        self.comboBox_ground_electrode_vertical_diameter = QtWidgets.QComboBox(self.groupBox_17)
        self.comboBox_ground_electrode_vertical_diameter.setObjectName("comboBox_ground_electrode_vertical_diameter")
        self.comboBox_ground_electrode_vertical_diameter.addItem("")
        self.comboBox_ground_electrode_vertical_diameter.addItem("")
        self.comboBox_ground_electrode_vertical_diameter.addItem("")
        self.comboBox_ground_electrode_vertical_diameter.addItem("")
        self.comboBox_ground_electrode_vertical_diameter.addItem("")
        self.comboBox_ground_electrode_vertical_diameter.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_ground_electrode_vertical_diameter, 2, 4, 1, 1)
        self.label_147 = QtWidgets.QLabel(self.groupBox_17)
        self.label_147.setObjectName("label_147")
        self.gridLayout_18.addWidget(self.label_147, 3, 0, 1, 1)
        self.doubleSpinBox_ground_electrode_vertical_climat_coeff = QtWidgets.QDoubleSpinBox(self.groupBox_17)
        self.doubleSpinBox_ground_electrode_vertical_climat_coeff.setProperty("value", 1.0)
        self.doubleSpinBox_ground_electrode_vertical_climat_coeff.setObjectName("doubleSpinBox_ground_electrode_vertical_climat_coeff")
        self.gridLayout_18.addWidget(self.doubleSpinBox_ground_electrode_vertical_climat_coeff, 3, 2, 1, 1)
        self.comboBox_ground_electrode_vertical_climat_coeff = QtWidgets.QComboBox(self.groupBox_17)
        self.comboBox_ground_electrode_vertical_climat_coeff.setObjectName("comboBox_ground_electrode_vertical_climat_coeff")
        self.comboBox_ground_electrode_vertical_climat_coeff.addItem("")
        self.comboBox_ground_electrode_vertical_climat_coeff.addItem("")
        self.comboBox_ground_electrode_vertical_climat_coeff.addItem("")
        self.comboBox_ground_electrode_vertical_climat_coeff.addItem("")
        self.comboBox_ground_electrode_vertical_climat_coeff.addItem("")
        self.comboBox_ground_electrode_vertical_climat_coeff.addItem("")
        self.comboBox_ground_electrode_vertical_climat_coeff.addItem("")
        self.comboBox_ground_electrode_vertical_climat_coeff.addItem("")
        self.comboBox_ground_electrode_vertical_climat_coeff.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_ground_electrode_vertical_climat_coeff, 3, 4, 1, 1)
        self.gridLayout_18.setColumnStretch(0, 7)
        self.gridLayout_18.setColumnStretch(2, 2)
        self.gridLayout_18.setColumnStretch(3, 1)
        self.gridLayout_18.setColumnStretch(4, 3)
        self.verticalLayout_13.addLayout(self.gridLayout_18)
        self.gridLayout_15.addWidget(self.groupBox_17, 3, 0, 1, 1)
        self.groupBox_contoured = QtWidgets.QGroupBox(self.tab_init_data)
        self.groupBox_contoured.setObjectName("groupBox_contoured")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_contoured)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_149 = QtWidgets.QLabel(self.groupBox_contoured)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_149.setFont(font)
        self.label_149.setObjectName("label_149")
        self.gridLayout_19.addWidget(self.label_149, 1, 3, 1, 1)
        self.spinBox_ground_electrode_horizontal_width = QtWidgets.QSpinBox(self.groupBox_contoured)
        self.spinBox_ground_electrode_horizontal_width.setObjectName("spinBox_ground_electrode_horizontal_width")
        self.gridLayout_19.addWidget(self.spinBox_ground_electrode_horizontal_width, 0, 2, 1, 1)
        self.label_148 = QtWidgets.QLabel(self.groupBox_contoured)
        self.label_148.setObjectName("label_148")
        self.gridLayout_19.addWidget(self.label_148, 0, 0, 1, 1)
        self.label_142 = QtWidgets.QLabel(self.groupBox_contoured)
        self.label_142.setObjectName("label_142")
        self.gridLayout_19.addWidget(self.label_142, 1, 0, 1, 1)
        self.doubleSpinBox_ground_electrode_horizontal_depth = QtWidgets.QDoubleSpinBox(self.groupBox_contoured)
        self.doubleSpinBox_ground_electrode_horizontal_depth.setObjectName("doubleSpinBox_ground_electrode_horizontal_depth")
        self.gridLayout_19.addWidget(self.doubleSpinBox_ground_electrode_horizontal_depth, 1, 2, 1, 1)
        self.comboBox_ground_electrode_horizontal_width = QtWidgets.QComboBox(self.groupBox_contoured)
        self.comboBox_ground_electrode_horizontal_width.setObjectName("comboBox_ground_electrode_horizontal_width")
        self.comboBox_ground_electrode_horizontal_width.addItem("")
        self.comboBox_ground_electrode_horizontal_width.addItem("")
        self.comboBox_ground_electrode_horizontal_width.addItem("")
        self.comboBox_ground_electrode_horizontal_width.addItem("")
        self.gridLayout_19.addWidget(self.comboBox_ground_electrode_horizontal_width, 0, 4, 1, 1)
        self.label_146 = QtWidgets.QLabel(self.groupBox_contoured)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_146.setFont(font)
        self.label_146.setObjectName("label_146")
        self.gridLayout_19.addWidget(self.label_146, 0, 3, 1, 1)
        self.comboBox_ground_electrode_horizontal_depth = QtWidgets.QComboBox(self.groupBox_contoured)
        self.comboBox_ground_electrode_horizontal_depth.setObjectName("comboBox_ground_electrode_horizontal_depth")
        self.comboBox_ground_electrode_horizontal_depth.addItem("")
        self.comboBox_ground_electrode_horizontal_depth.addItem("")
        self.comboBox_ground_electrode_horizontal_depth.addItem("")
        self.comboBox_ground_electrode_horizontal_depth.addItem("")
        self.comboBox_ground_electrode_horizontal_depth.addItem("")
        self.gridLayout_19.addWidget(self.comboBox_ground_electrode_horizontal_depth, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem3, 1, 1, 1, 1)
        self.label_132 = QtWidgets.QLabel(self.groupBox_contoured)
        self.label_132.setObjectName("label_132")
        self.gridLayout_19.addWidget(self.label_132, 2, 0, 1, 1)
        self.doubleSpinBox_ground_electrode_horizontal_climat_coeff = QtWidgets.QDoubleSpinBox(self.groupBox_contoured)
        self.doubleSpinBox_ground_electrode_horizontal_climat_coeff.setProperty("value", 1.0)
        self.doubleSpinBox_ground_electrode_horizontal_climat_coeff.setObjectName("doubleSpinBox_ground_electrode_horizontal_climat_coeff")
        self.gridLayout_19.addWidget(self.doubleSpinBox_ground_electrode_horizontal_climat_coeff, 2, 2, 1, 1)
        self.comboBox_ground_electrode_horizontal_climat_coeff = QtWidgets.QComboBox(self.groupBox_contoured)
        self.comboBox_ground_electrode_horizontal_climat_coeff.setObjectName("comboBox_ground_electrode_horizontal_climat_coeff")
        self.comboBox_ground_electrode_horizontal_climat_coeff.addItem("")
        self.comboBox_ground_electrode_horizontal_climat_coeff.addItem("")
        self.comboBox_ground_electrode_horizontal_climat_coeff.addItem("")
        self.comboBox_ground_electrode_horizontal_climat_coeff.addItem("")
        self.comboBox_ground_electrode_horizontal_climat_coeff.addItem("")
        self.gridLayout_19.addWidget(self.comboBox_ground_electrode_horizontal_climat_coeff, 2, 4, 1, 1)
        self.gridLayout_19.setColumnStretch(0, 7)
        self.gridLayout_19.setColumnStretch(2, 2)
        self.gridLayout_19.setColumnStretch(3, 1)
        self.gridLayout_19.setColumnStretch(4, 3)
        self.verticalLayout_12.addLayout(self.gridLayout_19)
        self.gridLayout_15.addWidget(self.groupBox_contoured, 4, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_init_data)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_9 = QtWidgets.QLabel(self.groupBox_14)
        self.label_9.setLineWidth(1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_17.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_14)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_17.addWidget(self.label_12, 0, 3, 1, 1)
        self.doubleSpinBox_permissible_resistance = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_permissible_resistance.setDecimals(1)
        self.doubleSpinBox_permissible_resistance.setMaximum(1000.0)
        self.doubleSpinBox_permissible_resistance.setObjectName("doubleSpinBox_permissible_resistance")
        self.gridLayout_17.addWidget(self.doubleSpinBox_permissible_resistance, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem4, 0, 1, 1, 1)
        self.comboBox_permissible_resistance = QtWidgets.QComboBox(self.groupBox_14)
        self.comboBox_permissible_resistance.setObjectName("comboBox_permissible_resistance")
        self.comboBox_permissible_resistance.addItem("")
        self.comboBox_permissible_resistance.addItem("")
        self.comboBox_permissible_resistance.addItem("")
        self.comboBox_permissible_resistance.addItem("")
        self.comboBox_permissible_resistance.addItem("")
        self.comboBox_permissible_resistance.addItem("")
        self.comboBox_permissible_resistance.addItem("")
        self.comboBox_permissible_resistance.addItem("")
        self.comboBox_permissible_resistance.addItem("")
        self.comboBox_permissible_resistance.addItem("")
        self.gridLayout_17.addWidget(self.comboBox_permissible_resistance, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_14)
        self.label.setObjectName("label")
        self.gridLayout_17.addWidget(self.label, 1, 0, 1, 1)
        self.doubleSpinBox_natural_grounding_resistance = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_natural_grounding_resistance.setObjectName("doubleSpinBox_natural_grounding_resistance")
        self.gridLayout_17.addWidget(self.doubleSpinBox_natural_grounding_resistance, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_14)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_17.addWidget(self.label_2, 1, 3, 1, 1)
        self.gridLayout_17.setColumnStretch(0, 7)
        self.gridLayout_17.setColumnStretch(2, 2)
        self.gridLayout_17.setColumnStretch(3, 1)
        self.gridLayout_17.setColumnStretch(4, 3)
        self.verticalLayout_15.addLayout(self.gridLayout_17)
        self.gridLayout_15.addWidget(self.groupBox_14, 1, 0, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_init_data)
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.spinBox_a_div_l = QtWidgets.QSpinBox(self.groupBox_19)
        self.spinBox_a_div_l.setMinimum(1)
        self.spinBox_a_div_l.setMaximum(3)
        self.spinBox_a_div_l.setObjectName("spinBox_a_div_l")
        self.gridLayout_20.addWidget(self.spinBox_a_div_l, 1, 2, 1, 1)
        self.label_135 = QtWidgets.QLabel(self.groupBox_19)
        self.label_135.setObjectName("label_135")
        self.gridLayout_20.addWidget(self.label_135, 0, 0, 1, 1)
        self.label__a_div_l = QtWidgets.QLabel(self.groupBox_19)
        self.label__a_div_l.setObjectName("label__a_div_l")
        self.gridLayout_20.addWidget(self.label__a_div_l, 1, 0, 1, 1)
        self.doubleSpinBox_grounding_contour_width = QtWidgets.QDoubleSpinBox(self.groupBox_19)
        self.doubleSpinBox_grounding_contour_width.setObjectName("doubleSpinBox_grounding_contour_width")
        self.gridLayout_20.addWidget(self.doubleSpinBox_grounding_contour_width, 4, 2, 1, 1)
        self.label_137 = QtWidgets.QLabel(self.groupBox_19)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_137.setFont(font)
        self.label_137.setObjectName("label_137")
        self.gridLayout_20.addWidget(self.label_137, 3, 3, 1, 1)
        self.doubleSpinBox_ground_electrode_horizontal_length = QtWidgets.QDoubleSpinBox(self.groupBox_19)
        self.doubleSpinBox_ground_electrode_horizontal_length.setObjectName("doubleSpinBox_ground_electrode_horizontal_length")
        self.gridLayout_20.addWidget(self.doubleSpinBox_ground_electrode_horizontal_length, 3, 2, 1, 1)
        self.label_grounding_contour_width = QtWidgets.QLabel(self.groupBox_19)
        self.label_grounding_contour_width.setObjectName("label_grounding_contour_width")
        self.gridLayout_20.addWidget(self.label_grounding_contour_width, 4, 0, 1, 1)
        self.comboBox_contoured = QtWidgets.QComboBox(self.groupBox_19)
        self.comboBox_contoured.setObjectName("comboBox_contoured")
        self.comboBox_contoured.addItem("")
        self.comboBox_contoured.addItem("")
        self.gridLayout_20.addWidget(self.comboBox_contoured, 0, 2, 1, 1)
        self.label_134 = QtWidgets.QLabel(self.groupBox_19)
        self.label_134.setObjectName("label_134")
        self.gridLayout_20.addWidget(self.label_134, 3, 0, 1, 1)
        self.label_138 = QtWidgets.QLabel(self.groupBox_19)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_138.setFont(font)
        self.label_138.setObjectName("label_138")
        self.gridLayout_20.addWidget(self.label_138, 4, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem5, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_19)
        self.label_5.setObjectName("label_5")
        self.gridLayout_20.addWidget(self.label_5, 2, 0, 1, 1)
        self.spinBox_ground_electrode_vertical_number = QtWidgets.QSpinBox(self.groupBox_19)
        self.spinBox_ground_electrode_vertical_number.setMinimum(1)
        self.spinBox_ground_electrode_vertical_number.setMaximum(200)
        self.spinBox_ground_electrode_vertical_number.setObjectName("spinBox_ground_electrode_vertical_number")
        self.gridLayout_20.addWidget(self.spinBox_ground_electrode_vertical_number, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_19)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_20.addWidget(self.label_8, 2, 3, 1, 1)
        self.gridLayout_20.setColumnStretch(0, 7)
        self.verticalLayout_16.addLayout(self.gridLayout_20)
        self.gridLayout_15.addWidget(self.groupBox_19, 5, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem6, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tab_init_data, "")
        self.tab_calc_results = QtWidgets.QWidget()
        self.tab_calc_results.setObjectName("tab_calc_results")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_calc_results)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_calc_results)
        self.groupBox_20.setObjectName("groupBox_20")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_4 = QtWidgets.QLabel(self.groupBox_20)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_21.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_n = QtWidgets.QLabel(self.groupBox_20)
        self.label_n.setAlignment(QtCore.Qt.AlignCenter)
        self.label_n.setObjectName("label_n")
        self.gridLayout_21.addWidget(self.label_n, 15, 2, 1, 1)
        self.label_Ip0max_1ph_25 = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ip0max_1ph_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_25.setObjectName("label_Ip0max_1ph_25")
        self.gridLayout_21.addWidget(self.label_Ip0max_1ph_25, 15, 0, 1, 1)
        self.label_n_pr = QtWidgets.QLabel(self.groupBox_20)
        self.label_n_pr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_n_pr.setObjectName("label_n_pr")
        self.gridLayout_21.addWidget(self.label_n_pr, 6, 2, 1, 1)
        self.label_151 = QtWidgets.QLabel(self.groupBox_20)
        self.label_151.setObjectName("label_151")
        self.gridLayout_21.addWidget(self.label_151, 2, 0, 1, 1)
        self.label_152 = QtWidgets.QLabel(self.groupBox_20)
        self.label_152.setAlignment(QtCore.Qt.AlignCenter)
        self.label_152.setObjectName("label_152")
        self.gridLayout_21.addWidget(self.label_152, 2, 1, 1, 1)
        self.label_155 = QtWidgets.QLabel(self.groupBox_20)
        self.label_155.setAlignment(QtCore.Qt.AlignCenter)
        self.label_155.setObjectName("label_155")
        self.gridLayout_21.addWidget(self.label_155, 6, 1, 1, 1)
        self.label_R_v = QtWidgets.QLabel(self.groupBox_20)
        self.label_R_v.setAlignment(QtCore.Qt.AlignCenter)
        self.label_R_v.setObjectName("label_R_v")
        self.gridLayout_21.addWidget(self.label_R_v, 13, 2, 1, 1)
        self.label_R_h = QtWidgets.QLabel(self.groupBox_20)
        self.label_R_h.setAlignment(QtCore.Qt.AlignCenter)
        self.label_R_h.setObjectName("label_R_h")
        self.gridLayout_21.addWidget(self.label_R_h, 11, 2, 1, 1)
        self.label_R_vo = QtWidgets.QLabel(self.groupBox_20)
        self.label_R_vo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_R_vo.setObjectName("label_R_vo")
        self.gridLayout_21.addWidget(self.label_R_vo, 4, 2, 1, 1)
        self.label_t = QtWidgets.QLabel(self.groupBox_20)
        self.label_t.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t.setObjectName("label_t")
        self.gridLayout_21.addWidget(self.label_t, 3, 2, 1, 1)
        self.label_ro = QtWidgets.QLabel(self.groupBox_20)
        self.label_ro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ro.setObjectName("label_ro")
        self.gridLayout_21.addWidget(self.label_ro, 2, 2, 1, 1)
        self.label_159 = QtWidgets.QLabel(self.groupBox_20)
        self.label_159.setAlignment(QtCore.Qt.AlignCenter)
        self.label_159.setObjectName("label_159")
        self.gridLayout_21.addWidget(self.label_159, 13, 1, 1, 1)
        self.label_133 = QtWidgets.QLabel(self.groupBox_20)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_133.setFont(font)
        self.label_133.setAlignment(QtCore.Qt.AlignCenter)
        self.label_133.setObjectName("label_133")
        self.gridLayout_21.addWidget(self.label_133, 0, 0, 1, 1)
        self.label_153 = QtWidgets.QLabel(self.groupBox_20)
        self.label_153.setAlignment(QtCore.Qt.AlignCenter)
        self.label_153.setObjectName("label_153")
        self.gridLayout_21.addWidget(self.label_153, 4, 1, 1, 1)
        self.label_157 = QtWidgets.QLabel(self.groupBox_20)
        self.label_157.setAlignment(QtCore.Qt.AlignCenter)
        self.label_157.setObjectName("label_157")
        self.gridLayout_21.addWidget(self.label_157, 9, 1, 1, 1)
        self.label_L_h = QtWidgets.QLabel(self.groupBox_20)
        self.label_L_h.setAlignment(QtCore.Qt.AlignCenter)
        self.label_L_h.setObjectName("label_L_h")
        self.gridLayout_21.addWidget(self.label_L_h, 9, 2, 1, 1)
        self.label_Ki_h = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ki_h.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ki_h.setObjectName("label_Ki_h")
        self.gridLayout_21.addWidget(self.label_Ki_h, 10, 2, 1, 1)
        self.label_160 = QtWidgets.QLabel(self.groupBox_20)
        self.label_160.setAlignment(QtCore.Qt.AlignCenter)
        self.label_160.setObjectName("label_160")
        self.gridLayout_21.addWidget(self.label_160, 15, 1, 1, 1)
        self.label_139 = QtWidgets.QLabel(self.groupBox_20)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_139.setFont(font)
        self.label_139.setAlignment(QtCore.Qt.AlignCenter)
        self.label_139.setObjectName("label_139")
        self.gridLayout_21.addWidget(self.label_139, 0, 1, 1, 1)
        self.label_140 = QtWidgets.QLabel(self.groupBox_20)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_140.setFont(font)
        self.label_140.setAlignment(QtCore.Qt.AlignCenter)
        self.label_140.setObjectName("label_140")
        self.gridLayout_21.addWidget(self.label_140, 0, 2, 1, 1)
        self.label_158 = QtWidgets.QLabel(self.groupBox_20)
        self.label_158.setAlignment(QtCore.Qt.AlignCenter)
        self.label_158.setObjectName("label_158")
        self.gridLayout_21.addWidget(self.label_158, 11, 1, 1, 1)
        self.label_154 = QtWidgets.QLabel(self.groupBox_20)
        self.label_154.setAlignment(QtCore.Qt.AlignCenter)
        self.label_154.setObjectName("label_154")
        self.gridLayout_21.addWidget(self.label_154, 3, 1, 1, 1)
        self.label_k_Lh_to_Lv = QtWidgets.QLabel(self.groupBox_20)
        self.label_k_Lh_to_Lv.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_Lh_to_Lv.setObjectName("label_k_Lh_to_Lv")
        self.gridLayout_21.addWidget(self.label_k_Lh_to_Lv, 7, 2, 1, 1)
        self.label_a_div_l = QtWidgets.QLabel(self.groupBox_20)
        self.label_a_div_l.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_div_l.setObjectName("label_a_div_l")
        self.gridLayout_21.addWidget(self.label_a_div_l, 17, 2, 1, 1)
        self.label_Ip0max_1ph_15 = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ip0max_1ph_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_15.setObjectName("label_Ip0max_1ph_15")
        self.gridLayout_21.addWidget(self.label_Ip0max_1ph_15, 3, 0, 1, 1)
        self.label_Ip0max_1ph_16 = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ip0max_1ph_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_16.setObjectName("label_Ip0max_1ph_16")
        self.gridLayout_21.addWidget(self.label_Ip0max_1ph_16, 4, 0, 1, 1)
        self.label_Ip0max_1ph_17 = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ip0max_1ph_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_17.setObjectName("label_Ip0max_1ph_17")
        self.gridLayout_21.addWidget(self.label_Ip0max_1ph_17, 6, 0, 1, 1)
        self.label_Ip0max_1ph_18 = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ip0max_1ph_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_18.setObjectName("label_Ip0max_1ph_18")
        self.gridLayout_21.addWidget(self.label_Ip0max_1ph_18, 7, 0, 1, 1)
        self.label_Ip0max_1ph_21 = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ip0max_1ph_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_21.setObjectName("label_Ip0max_1ph_21")
        self.gridLayout_21.addWidget(self.label_Ip0max_1ph_21, 9, 0, 1, 1)
        self.label_Ip0max_1ph_22 = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ip0max_1ph_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_22.setObjectName("label_Ip0max_1ph_22")
        self.gridLayout_21.addWidget(self.label_Ip0max_1ph_22, 10, 0, 1, 1)
        self.label_Ip0max_1ph_23 = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ip0max_1ph_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_23.setObjectName("label_Ip0max_1ph_23")
        self.gridLayout_21.addWidget(self.label_Ip0max_1ph_23, 11, 0, 1, 1)
        self.label_Ip0max_1ph_24 = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ip0max_1ph_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_24.setObjectName("label_Ip0max_1ph_24")
        self.gridLayout_21.addWidget(self.label_Ip0max_1ph_24, 13, 0, 1, 1)
        self.label_Ip0max_1ph_26 = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ip0max_1ph_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_26.setObjectName("label_Ip0max_1ph_26")
        self.gridLayout_21.addWidget(self.label_Ip0max_1ph_26, 17, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_20)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_21.addWidget(self.label_7, 16, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_20)
        self.label_3.setObjectName("label_3")
        self.gridLayout_21.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_Rfull = QtWidgets.QLabel(self.groupBox_20)
        self.label_Rfull.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Rfull.setObjectName("label_Rfull")
        self.gridLayout_21.addWidget(self.label_Rfull, 16, 2, 1, 1)
        self.label_R_artificial = QtWidgets.QLabel(self.groupBox_20)
        self.label_R_artificial.setAlignment(QtCore.Qt.AlignCenter)
        self.label_R_artificial.setObjectName("label_R_artificial")
        self.gridLayout_21.addWidget(self.label_R_artificial, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_20)
        self.label_6.setObjectName("label_6")
        self.gridLayout_21.addWidget(self.label_6, 16, 0, 1, 1)
        self.label_Ip0max_1ph_19 = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ip0max_1ph_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_19.setObjectName("label_Ip0max_1ph_19")
        self.gridLayout_21.addWidget(self.label_Ip0max_1ph_19, 5, 0, 1, 1)
        self.label_Ki_v_pr = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ki_v_pr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ki_v_pr.setObjectName("label_Ki_v_pr")
        self.gridLayout_21.addWidget(self.label_Ki_v_pr, 5, 2, 1, 1)
        self.label_Ip0max_1ph_39 = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ip0max_1ph_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_39.setObjectName("label_Ip0max_1ph_39")
        self.gridLayout_21.addWidget(self.label_Ip0max_1ph_39, 14, 0, 1, 1)
        self.label_Ki_v = QtWidgets.QLabel(self.groupBox_20)
        self.label_Ki_v.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ki_v.setObjectName("label_Ki_v")
        self.gridLayout_21.addWidget(self.label_Ki_v, 14, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_20)
        self.label_20.setObjectName("label_20")
        self.gridLayout_21.addWidget(self.label_20, 8, 0, 1, 1)
        self.label_h = QtWidgets.QLabel(self.groupBox_20)
        self.label_h.setAlignment(QtCore.Qt.AlignCenter)
        self.label_h.setObjectName("label_h")
        self.gridLayout_21.addWidget(self.label_h, 8, 2, 1, 1)
        self.label_173 = QtWidgets.QLabel(self.groupBox_20)
        self.label_173.setAlignment(QtCore.Qt.AlignCenter)
        self.label_173.setObjectName("label_173")
        self.gridLayout_21.addWidget(self.label_173, 8, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_21)
        self.verticalLayout_3.addWidget(self.groupBox_20)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.tabWidget.addTab(self.tab_calc_results, "")
        self.tab_check_results = QtWidgets.QWidget()
        self.tab_check_results.setObjectName("tab_check_results")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_check_results)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_check_results)
        self.groupBox_21.setObjectName("groupBox_21")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_21)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_Ip0max_1ph_50 = QtWidgets.QLabel(self.groupBox_21)
        self.label_Ip0max_1ph_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_50.setObjectName("label_Ip0max_1ph_50")
        self.gridLayout_23.addWidget(self.label_Ip0max_1ph_50, 5, 0, 1, 1)
        self.label_176 = QtWidgets.QLabel(self.groupBox_21)
        self.label_176.setAlignment(QtCore.Qt.AlignCenter)
        self.label_176.setObjectName("label_176")
        self.gridLayout_23.addWidget(self.label_176, 6, 1, 1, 1)
        self.label_Ki_h_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_Ki_h_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ki_h_check.setObjectName("label_Ki_h_check")
        self.gridLayout_23.addWidget(self.label_Ki_h_check, 10, 2, 1, 1)
        self.label_a_div_l_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_a_div_l_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a_div_l_check.setObjectName("label_a_div_l_check")
        self.gridLayout_23.addWidget(self.label_a_div_l_check, 16, 2, 1, 1)
        self.label_Ip0max_1ph_47 = QtWidgets.QLabel(self.groupBox_21)
        self.label_Ip0max_1ph_47.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_47.setObjectName("label_Ip0max_1ph_47")
        self.gridLayout_23.addWidget(self.label_Ip0max_1ph_47, 6, 0, 1, 1)
        self.label_R_v_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_R_v_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_R_v_check.setObjectName("label_R_v_check")
        self.gridLayout_23.addWidget(self.label_R_v_check, 6, 2, 1, 1)
        self.label_k_Lh_to_Lv_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_k_Lh_to_Lv_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_Lh_to_Lv_check.setObjectName("label_k_Lh_to_Lv_check")
        self.gridLayout_23.addWidget(self.label_k_Lh_to_Lv_check, 7, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_21)
        self.label_23.setObjectName("label_23")
        self.gridLayout_23.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_Ip0max_1ph_48 = QtWidgets.QLabel(self.groupBox_21)
        self.label_Ip0max_1ph_48.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_48.setObjectName("label_Ip0max_1ph_48")
        self.gridLayout_23.addWidget(self.label_Ip0max_1ph_48, 16, 0, 1, 1)
        self.label_Ip0max_1ph_46 = QtWidgets.QLabel(self.groupBox_21)
        self.label_Ip0max_1ph_46.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_46.setObjectName("label_Ip0max_1ph_46")
        self.gridLayout_23.addWidget(self.label_Ip0max_1ph_46, 11, 0, 1, 1)
        self.label_R_h_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_R_h_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_R_h_check.setObjectName("label_R_h_check")
        self.gridLayout_23.addWidget(self.label_R_h_check, 11, 2, 1, 1)
        self.label_179 = QtWidgets.QLabel(self.groupBox_21)
        self.label_179.setAlignment(QtCore.Qt.AlignCenter)
        self.label_179.setObjectName("label_179")
        self.gridLayout_23.addWidget(self.label_179, 9, 1, 1, 1)
        self.label_t_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_t_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t_check.setObjectName("label_t_check")
        self.gridLayout_23.addWidget(self.label_t_check, 3, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_21)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_23.addWidget(self.label_22, 15, 1, 1, 1)
        self.label_Ip0max_1ph_20 = QtWidgets.QLabel(self.groupBox_21)
        self.label_Ip0max_1ph_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_20.setObjectName("label_Ip0max_1ph_20")
        self.gridLayout_23.addWidget(self.label_Ip0max_1ph_20, 3, 0, 1, 1)
        self.label_184 = QtWidgets.QLabel(self.groupBox_21)
        self.label_184.setAlignment(QtCore.Qt.AlignCenter)
        self.label_184.setObjectName("label_184")
        self.gridLayout_23.addWidget(self.label_184, 3, 1, 1, 1)
        self.label_Ip0max_1ph_43 = QtWidgets.QLabel(self.groupBox_21)
        self.label_Ip0max_1ph_43.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_43.setObjectName("label_Ip0max_1ph_43")
        self.gridLayout_23.addWidget(self.label_Ip0max_1ph_43, 7, 0, 1, 1)
        self.label_Rfull_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_Rfull_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Rfull_check.setObjectName("label_Rfull_check")
        self.gridLayout_23.addWidget(self.label_Rfull_check, 15, 2, 1, 1)
        self.label_156 = QtWidgets.QLabel(self.groupBox_21)
        self.label_156.setObjectName("label_156")
        self.gridLayout_23.addWidget(self.label_156, 2, 0, 1, 1)
        self.label_Ip0max_1ph_44 = QtWidgets.QLabel(self.groupBox_21)
        self.label_Ip0max_1ph_44.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_44.setObjectName("label_Ip0max_1ph_44")
        self.gridLayout_23.addWidget(self.label_Ip0max_1ph_44, 9, 0, 1, 1)
        self.label_Ip0max_1ph_45 = QtWidgets.QLabel(self.groupBox_21)
        self.label_Ip0max_1ph_45.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_45.setObjectName("label_Ip0max_1ph_45")
        self.gridLayout_23.addWidget(self.label_Ip0max_1ph_45, 10, 0, 1, 1)
        self.label_R_artificial_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_R_artificial_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_R_artificial_check.setObjectName("label_R_artificial_check")
        self.gridLayout_23.addWidget(self.label_R_artificial_check, 1, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_21)
        self.label_24.setObjectName("label_24")
        self.gridLayout_23.addWidget(self.label_24, 15, 0, 1, 1)
        self.label_182 = QtWidgets.QLabel(self.groupBox_21)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_182.setFont(font)
        self.label_182.setAlignment(QtCore.Qt.AlignCenter)
        self.label_182.setObjectName("label_182")
        self.gridLayout_23.addWidget(self.label_182, 0, 2, 1, 1)
        self.label_R_vo_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_R_vo_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_R_vo_check.setObjectName("label_R_vo_check")
        self.gridLayout_23.addWidget(self.label_R_vo_check, 4, 2, 1, 1)
        self.label_181 = QtWidgets.QLabel(self.groupBox_21)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_181.setFont(font)
        self.label_181.setAlignment(QtCore.Qt.AlignCenter)
        self.label_181.setObjectName("label_181")
        self.gridLayout_23.addWidget(self.label_181, 0, 1, 1, 1)
        self.label_Ip0max_1ph_41 = QtWidgets.QLabel(self.groupBox_21)
        self.label_Ip0max_1ph_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Ip0max_1ph_41.setObjectName("label_Ip0max_1ph_41")
        self.gridLayout_23.addWidget(self.label_Ip0max_1ph_41, 4, 0, 1, 1)
        self.label_177 = QtWidgets.QLabel(self.groupBox_21)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_177.setFont(font)
        self.label_177.setAlignment(QtCore.Qt.AlignCenter)
        self.label_177.setObjectName("label_177")
        self.gridLayout_23.addWidget(self.label_177, 0, 0, 1, 1)
        self.label_174 = QtWidgets.QLabel(self.groupBox_21)
        self.label_174.setAlignment(QtCore.Qt.AlignCenter)
        self.label_174.setObjectName("label_174")
        self.gridLayout_23.addWidget(self.label_174, 2, 1, 1, 1)
        self.label_ro_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_ro_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ro_check.setObjectName("label_ro_check")
        self.gridLayout_23.addWidget(self.label_ro_check, 2, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_21)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_23.addWidget(self.label_21, 1, 1, 1, 1)
        self.label_L_h_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_L_h_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_L_h_check.setObjectName("label_L_h_check")
        self.gridLayout_23.addWidget(self.label_L_h_check, 9, 2, 1, 1)
        self.label_178 = QtWidgets.QLabel(self.groupBox_21)
        self.label_178.setAlignment(QtCore.Qt.AlignCenter)
        self.label_178.setObjectName("label_178")
        self.gridLayout_23.addWidget(self.label_178, 4, 1, 1, 1)
        self.label_183 = QtWidgets.QLabel(self.groupBox_21)
        self.label_183.setAlignment(QtCore.Qt.AlignCenter)
        self.label_183.setObjectName("label_183")
        self.gridLayout_23.addWidget(self.label_183, 11, 1, 1, 1)
        self.label_Ki_v_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_Ki_v_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ki_v_check.setObjectName("label_Ki_v_check")
        self.gridLayout_23.addWidget(self.label_Ki_v_check, 5, 2, 1, 1)
        self.label_185 = QtWidgets.QLabel(self.groupBox_21)
        self.label_185.setAlignment(QtCore.Qt.AlignCenter)
        self.label_185.setObjectName("label_185")
        self.gridLayout_23.addWidget(self.label_185, 8, 1, 1, 1)
        self.label_h_check = QtWidgets.QLabel(self.groupBox_21)
        self.label_h_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_h_check.setObjectName("label_h_check")
        self.gridLayout_23.addWidget(self.label_h_check, 8, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_21)
        self.label_25.setObjectName("label_25")
        self.gridLayout_23.addWidget(self.label_25, 8, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_21)
        self.label_26.setObjectName("label_26")
        self.gridLayout_23.addWidget(self.label_26, 17, 0, 1, 1)
        self.label_result_check = QtWidgets.QLabel(self.groupBox_21)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_result_check.setFont(font)
        self.label_result_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result_check.setObjectName("label_result_check")
        self.gridLayout_23.addWidget(self.label_result_check, 17, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_23)
        self.verticalLayout_6.addWidget(self.groupBox_21)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.tabWidget.addTab(self.tab_check_results, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 25))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Calculation = QtWidgets.QMenu(self.menubar)
        self.menu_Calculation.setObjectName("menu_Calculation")
        self.menu_Report = QtWidgets.QMenu(self.menubar)
        self.menu_Report.setObjectName("menu_Report")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Calculate = QtWidgets.QAction(MainWindow)
        self.action_Calculate.setObjectName("action_Calculate")
        self.action_db = QtWidgets.QAction(MainWindow)
        self.action_db.setObjectName("action_db")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_ODT = QtWidgets.QAction(MainWindow)
        self.action_ODT.setObjectName("action_ODT")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Qt = QtWidgets.QAction(MainWindow)
        self.action_Qt.setObjectName("action_Qt")
        self.action_clean_form = QtWidgets.QAction(MainWindow)
        self.action_clean_form.setObjectName("action_clean_form")
        self.action_DOCX = QtWidgets.QAction(MainWindow)
        self.action_DOCX.setObjectName("action_DOCX")
        self.action_minimize_to_tray = QtWidgets.QAction(MainWindow)
        self.action_minimize_to_tray.setCheckable(True)
        self.action_minimize_to_tray.setObjectName("action_minimize_to_tray")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_Calculation.addAction(self.action_Calculate)
        self.menu_Calculation.addAction(self.action_clean_form)
        self.menu_Report.addAction(self.action_ODT)
        self.menu_Report.addAction(self.action_DOCX)
        self.menu_Help.addAction(self.action_db)
        self.menu_Help.addSeparator()
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_minimize_to_tray)
        self.menu.addAction(self.action_About)
        self.menu.addAction(self.action_Qt)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Calculation.menuAction())
        self.menubar.addAction(self.menu_Report.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.action_clean_form.triggered.connect(MainWindow.clean_form)
        self.action_DOCX.triggered.connect(MainWindow.save_report_docx)
        self.comboBox_soil_resistivity_high.currentTextChanged['QString'].connect(MainWindow.on_clicked_comboBox_soil_resistivity_high)
        self.comboBox_soil_resistivity_low.currentTextChanged['QString'].connect(MainWindow.on_clicked_comboBox_soil_resistivity_low)
        self.comboBox_permissible_resistance.currentTextChanged['QString'].connect(MainWindow.on_clicked_comboBox_permissible_resistance)
        self.comboBox_ground_electrode_vertical_length.currentTextChanged['QString'].connect(MainWindow.on_clicked_comboBox_ground_electrode_vertical_length)
        self.comboBox_ground_electrode_vertical_diameter.currentTextChanged['QString'].connect(MainWindow.on_clicked_comboBox_ground_electrode_vertical_diameter)
        self.comboBox_ground_electrode_horizontal_width.currentTextChanged['QString'].connect(MainWindow.on_clicked_comboBox_ground_electrode_horizontal_width)
        self.comboBox_ground_electrode_horizontal_depth.currentTextChanged['QString'].connect(MainWindow.on_clicked_comboBox_ground_electrode_horizontal_depth)
        self.comboBox_ground_electrode_horizontal_climat_coeff.currentTextChanged['QString'].connect(MainWindow.on_clicked_comboBox_ground_electrode_horizontal_climat_coeff)
        self.comboBox_ground_electrode_vertical_climat_coeff.currentTextChanged['QString'].connect(MainWindow.on_clicked_comboBox_ground_electrode_vertical_climat_coeff)
        self.comboBox_contoured.currentIndexChanged['int'].connect(MainWindow.on_clicked_comboBox_contoured)
        self.radioButton_2.toggled['bool'].connect(self.label_grounding_contour_width.setVisible)
        self.radioButton_2.toggled['bool'].connect(self.doubleSpinBox_grounding_contour_width.setVisible)
        self.radioButton_2.toggled['bool'].connect(self.label_138.setVisible)
        self.radioButton_2.toggled['bool'].connect(self.label_134.setVisible)
        self.radioButton_2.toggled['bool'].connect(self.doubleSpinBox_ground_electrode_horizontal_length.setVisible)
        self.radioButton_2.toggled['bool'].connect(self.label_137.setVisible)
        self.radioButton.toggled['bool'].connect(self.label__a_div_l.setVisible)
        self.radioButton.toggled['bool'].connect(self.spinBox_a_div_l.setVisible)
        self.action_Qt.triggered.connect(MainWindow.show_aboutqt_window)
        self.action_About.triggered.connect(MainWindow.show_about_window)
        self.action_Open.triggered.connect(MainWindow.open_file_dialog)
        self.action_Save.triggered.connect(MainWindow.save_file_dialog)
        self.action_minimize_to_tray.triggered.connect(MainWindow.checked_action_minimize_to_tray)
        self.action_Exit.triggered.connect(MainWindow.close)
        self.action_ODT.triggered.connect(MainWindow.save_report_odt)
        self.action_Calculate.triggered.connect(MainWindow.start_calculation)
        self.radioButton_2.toggled['bool'].connect(self.label_5.setVisible)
        self.radioButton_2.toggled['bool'].connect(self.spinBox_ground_electrode_vertical_number.setVisible)
        self.radioButton_2.toggled['bool'].connect(self.label_8.setVisible)
        self.action_db.triggered.connect(MainWindow.show_db_window)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.doubleSpinBox_permissible_resistance)
        MainWindow.setTabOrder(self.doubleSpinBox_permissible_resistance, self.comboBox_permissible_resistance)
        MainWindow.setTabOrder(self.comboBox_permissible_resistance, self.doubleSpinBox_natural_grounding_resistance)
        MainWindow.setTabOrder(self.doubleSpinBox_natural_grounding_resistance, self.doubleSpinBox_soil_high_level_depth)
        MainWindow.setTabOrder(self.doubleSpinBox_soil_high_level_depth, self.spinBox_soil_resistivity_high)
        MainWindow.setTabOrder(self.spinBox_soil_resistivity_high, self.comboBox_soil_resistivity_high)
        MainWindow.setTabOrder(self.comboBox_soil_resistivity_high, self.spinBox_soil_resistivity_low)
        MainWindow.setTabOrder(self.spinBox_soil_resistivity_low, self.comboBox_soil_resistivity_low)
        MainWindow.setTabOrder(self.comboBox_soil_resistivity_low, self.doubleSpinBox_ground_electrode_vertical_length)
        MainWindow.setTabOrder(self.doubleSpinBox_ground_electrode_vertical_length, self.comboBox_ground_electrode_vertical_length)
        MainWindow.setTabOrder(self.comboBox_ground_electrode_vertical_length, self.comboBox_ground_electrode_vertical_type)
        MainWindow.setTabOrder(self.comboBox_ground_electrode_vertical_type, self.spinBox_ground_electrode_vertical_diameter)
        MainWindow.setTabOrder(self.spinBox_ground_electrode_vertical_diameter, self.comboBox_ground_electrode_vertical_diameter)
        MainWindow.setTabOrder(self.comboBox_ground_electrode_vertical_diameter, self.doubleSpinBox_ground_electrode_vertical_climat_coeff)
        MainWindow.setTabOrder(self.doubleSpinBox_ground_electrode_vertical_climat_coeff, self.comboBox_ground_electrode_vertical_climat_coeff)
        MainWindow.setTabOrder(self.comboBox_ground_electrode_vertical_climat_coeff, self.spinBox_ground_electrode_horizontal_width)
        MainWindow.setTabOrder(self.spinBox_ground_electrode_horizontal_width, self.comboBox_ground_electrode_horizontal_width)
        MainWindow.setTabOrder(self.comboBox_ground_electrode_horizontal_width, self.doubleSpinBox_ground_electrode_horizontal_depth)
        MainWindow.setTabOrder(self.doubleSpinBox_ground_electrode_horizontal_depth, self.comboBox_ground_electrode_horizontal_depth)
        MainWindow.setTabOrder(self.comboBox_ground_electrode_horizontal_depth, self.doubleSpinBox_ground_electrode_horizontal_climat_coeff)
        MainWindow.setTabOrder(self.doubleSpinBox_ground_electrode_horizontal_climat_coeff, self.comboBox_ground_electrode_horizontal_climat_coeff)
        MainWindow.setTabOrder(self.comboBox_ground_electrode_horizontal_climat_coeff, self.comboBox_contoured)
        MainWindow.setTabOrder(self.comboBox_contoured, self.spinBox_a_div_l)
        MainWindow.setTabOrder(self.spinBox_a_div_l, self.doubleSpinBox_ground_electrode_horizontal_length)
        MainWindow.setTabOrder(self.doubleSpinBox_ground_electrode_horizontal_length, self.doubleSpinBox_grounding_contour_width)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Программа для расчёта заземляющих устройств"))
        self.groupBox.setTitle(_translate("MainWindow", "Режим"))
        self.radioButton.setText(_translate("MainWindow", "Расчёт заземляющего устройства"))
        self.radioButton_2.setText(_translate("MainWindow", "Проверка заземляющего устройства"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Свойства грунта"))
        self.label_10.setText(_translate("MainWindow", "Толщина верхнего слоя грунта (H)"))
        self.label_14.setText(_translate("MainWindow", "Ом·м"))
        self.label_13.setText(_translate("MainWindow", "м"))
        self.label_11.setText(_translate("MainWindow", "Удельное сопротивление верхнего слоя грунта"))
        self.label_15.setText(_translate("MainWindow", "Удельное сопротивление нижнего слоя грунта"))
        self.label_131.setText(_translate("MainWindow", "Ом·м"))
        self.comboBox_soil_resistivity_high.setItemText(0, _translate("MainWindow", "Выбрать из списка значений"))
        self.comboBox_soil_resistivity_high.setItemText(1, _translate("MainWindow", "Глина - 70"))
        self.comboBox_soil_resistivity_high.setItemText(2, _translate("MainWindow", "Глина каменистая - 100"))
        self.comboBox_soil_resistivity_high.setItemText(3, _translate("MainWindow", "Земля садовая - 50"))
        self.comboBox_soil_resistivity_high.setItemText(4, _translate("MainWindow", "Известняк - 2000"))
        self.comboBox_soil_resistivity_high.setItemText(5, _translate("MainWindow", "Лёсс - 250"))
        self.comboBox_soil_resistivity_high.setItemText(6, _translate("MainWindow", "Мергель - 2000"))
        self.comboBox_soil_resistivity_high.setItemText(7, _translate("MainWindow", "Песок - 500"))
        self.comboBox_soil_resistivity_high.setItemText(8, _translate("MainWindow", "Песок крупнозернистый с валунами - 1000"))
        self.comboBox_soil_resistivity_high.setItemText(9, _translate("MainWindow", "Скала - 4000"))
        self.comboBox_soil_resistivity_high.setItemText(10, _translate("MainWindow", "Суглинок - 100"))
        self.comboBox_soil_resistivity_high.setItemText(11, _translate("MainWindow", "Супесь - 300"))
        self.comboBox_soil_resistivity_high.setItemText(12, _translate("MainWindow", "Торф - 20"))
        self.comboBox_soil_resistivity_high.setItemText(13, _translate("MainWindow", "Чернозём - 30"))
        self.comboBox_soil_resistivity_high.setItemText(14, _translate("MainWindow", "Вода грунтовая - 50"))
        self.comboBox_soil_resistivity_high.setItemText(15, _translate("MainWindow", "Вода морская - 3"))
        self.comboBox_soil_resistivity_high.setItemText(16, _translate("MainWindow", "Вода прудовая - 50"))
        self.comboBox_soil_resistivity_high.setItemText(17, _translate("MainWindow", "Вода речная - 100"))
        self.comboBox_soil_resistivity_low.setItemText(0, _translate("MainWindow", "Выбрать из списка значений"))
        self.comboBox_soil_resistivity_low.setItemText(1, _translate("MainWindow", "Глина - 70"))
        self.comboBox_soil_resistivity_low.setItemText(2, _translate("MainWindow", "Глина каменистая - 100"))
        self.comboBox_soil_resistivity_low.setItemText(3, _translate("MainWindow", "Земля садовая - 50"))
        self.comboBox_soil_resistivity_low.setItemText(4, _translate("MainWindow", "Известняк - 2000"))
        self.comboBox_soil_resistivity_low.setItemText(5, _translate("MainWindow", "Лёсс - 250"))
        self.comboBox_soil_resistivity_low.setItemText(6, _translate("MainWindow", "Мергель - 2000"))
        self.comboBox_soil_resistivity_low.setItemText(7, _translate("MainWindow", "Песок - 500"))
        self.comboBox_soil_resistivity_low.setItemText(8, _translate("MainWindow", "Песок крупнозернистый с валунами - 1000"))
        self.comboBox_soil_resistivity_low.setItemText(9, _translate("MainWindow", "Скала - 4000"))
        self.comboBox_soil_resistivity_low.setItemText(10, _translate("MainWindow", "Суглинок - 100"))
        self.comboBox_soil_resistivity_low.setItemText(11, _translate("MainWindow", "Супесь - 300"))
        self.comboBox_soil_resistivity_low.setItemText(12, _translate("MainWindow", "Торф - 20"))
        self.comboBox_soil_resistivity_low.setItemText(13, _translate("MainWindow", "Чернозём - 30"))
        self.comboBox_soil_resistivity_low.setItemText(14, _translate("MainWindow", "Вода грунтовая - 50"))
        self.comboBox_soil_resistivity_low.setItemText(15, _translate("MainWindow", "Вода морская - 3"))
        self.comboBox_soil_resistivity_low.setItemText(16, _translate("MainWindow", "Вода прудовая - 50"))
        self.comboBox_soil_resistivity_low.setItemText(17, _translate("MainWindow", "Вода речная - 100"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Вертикальный заземлитель"))
        self.comboBox_ground_electrode_vertical_length.setItemText(0, _translate("MainWindow", "Выбрать из списка значений"))
        self.comboBox_ground_electrode_vertical_length.setItemText(1, _translate("MainWindow", "2.0"))
        self.comboBox_ground_electrode_vertical_length.setItemText(2, _translate("MainWindow", "2.5"))
        self.comboBox_ground_electrode_vertical_length.setItemText(3, _translate("MainWindow", "3.0"))
        self.comboBox_ground_electrode_vertical_length.setItemText(4, _translate("MainWindow", "3.5"))
        self.comboBox_ground_electrode_vertical_length.setItemText(5, _translate("MainWindow", "4.0"))
        self.comboBox_ground_electrode_vertical_length.setItemText(6, _translate("MainWindow", "4.5"))
        self.comboBox_ground_electrode_vertical_length.setItemText(7, _translate("MainWindow", "5.0"))
        self.label_150.setText(_translate("MainWindow", "мм"))
        self.label_145.setText(_translate("MainWindow", "м"))
        self.label_144.setText(_translate("MainWindow", "Диаметр стержня (ширина полки уголка d)"))
        self.comboBox_ground_electrode_vertical_type.setItemText(0, _translate("MainWindow", "Стальной стержень, круглого сечения"))
        self.comboBox_ground_electrode_vertical_type.setItemText(1, _translate("MainWindow", "Уголковая сталь"))
        self.label_141.setText(_translate("MainWindow", "Тип вертикального заземлителя"))
        self.label_143.setText(_translate("MainWindow", "Длина вертикального заземлителя (L=2-5 м)"))
        self.comboBox_ground_electrode_vertical_diameter.setItemText(0, _translate("MainWindow", "Выбрать из списка значений"))
        self.comboBox_ground_electrode_vertical_diameter.setItemText(1, _translate("MainWindow", "25"))
        self.comboBox_ground_electrode_vertical_diameter.setItemText(2, _translate("MainWindow", "30"))
        self.comboBox_ground_electrode_vertical_diameter.setItemText(3, _translate("MainWindow", "40"))
        self.comboBox_ground_electrode_vertical_diameter.setItemText(4, _translate("MainWindow", "50"))
        self.comboBox_ground_electrode_vertical_diameter.setItemText(5, _translate("MainWindow", "60"))
        self.label_147.setText(_translate("MainWindow", "Климатический коэффициент\n"
" для вертикальных электродов"))
        self.comboBox_ground_electrode_vertical_climat_coeff.setItemText(0, _translate("MainWindow", "Выбрать из списка значений"))
        self.comboBox_ground_electrode_vertical_climat_coeff.setItemText(1, _translate("MainWindow", "(Зона I L=2-3 м H=0.5-0.8 м) - 1.9"))
        self.comboBox_ground_electrode_vertical_climat_coeff.setItemText(2, _translate("MainWindow", "(Зона I L=5 м H=0.7-0.8 м) - 1.35"))
        self.comboBox_ground_electrode_vertical_climat_coeff.setItemText(3, _translate("MainWindow", "(Зона II L=2-3 м H=0.5-0.8 м) - 1.65"))
        self.comboBox_ground_electrode_vertical_climat_coeff.setItemText(4, _translate("MainWindow", "(Зона II L=5 м H=0.7-0.8 м) - 1.25"))
        self.comboBox_ground_electrode_vertical_climat_coeff.setItemText(5, _translate("MainWindow", "(Зона III L=2-3 м H=0.5-0.8 м) - 1.5"))
        self.comboBox_ground_electrode_vertical_climat_coeff.setItemText(6, _translate("MainWindow", "(Зона III L=5 м H=0.7-0.8 м) - 1.15"))
        self.comboBox_ground_electrode_vertical_climat_coeff.setItemText(7, _translate("MainWindow", "(Зона IV L=2-3 м H=0.5-0.8 м) - 1.75"))
        self.comboBox_ground_electrode_vertical_climat_coeff.setItemText(8, _translate("MainWindow", "(Зона IV L=5 м H=0.7-0.8 м) - 1.1"))
        self.groupBox_contoured.setTitle(_translate("MainWindow", "Горизонтальный заземлитель"))
        self.label_149.setText(_translate("MainWindow", "м"))
        self.label_148.setText(_translate("MainWindow", "Ширина соединительной полосы (b)"))
        self.label_142.setText(_translate("MainWindow", "Глубина заложения горизонтального заземлителя (t=0,5-0,8 м)"))
        self.comboBox_ground_electrode_horizontal_width.setItemText(0, _translate("MainWindow", "Выбрать из списка значений"))
        self.comboBox_ground_electrode_horizontal_width.setItemText(1, _translate("MainWindow", "30"))
        self.comboBox_ground_electrode_horizontal_width.setItemText(2, _translate("MainWindow", "40"))
        self.comboBox_ground_electrode_horizontal_width.setItemText(3, _translate("MainWindow", "50"))
        self.label_146.setText(_translate("MainWindow", "мм"))
        self.comboBox_ground_electrode_horizontal_depth.setItemText(0, _translate("MainWindow", "Выбрать из списка значений"))
        self.comboBox_ground_electrode_horizontal_depth.setItemText(1, _translate("MainWindow", "0.5"))
        self.comboBox_ground_electrode_horizontal_depth.setItemText(2, _translate("MainWindow", "0.6"))
        self.comboBox_ground_electrode_horizontal_depth.setItemText(3, _translate("MainWindow", "0.7"))
        self.comboBox_ground_electrode_horizontal_depth.setItemText(4, _translate("MainWindow", "0.8"))
        self.label_132.setText(_translate("MainWindow", "Климатический коэффициент для горизонтальной полосы"))
        self.comboBox_ground_electrode_horizontal_climat_coeff.setItemText(0, _translate("MainWindow", "Выбрать из списка значений"))
        self.comboBox_ground_electrode_horizontal_climat_coeff.setItemText(1, _translate("MainWindow", "(Зона I H=0.5-0.8 м) - 5.75"))
        self.comboBox_ground_electrode_horizontal_climat_coeff.setItemText(2, _translate("MainWindow", "(Зона II H=0.5-0.8 м) - 4.00"))
        self.comboBox_ground_electrode_horizontal_climat_coeff.setItemText(3, _translate("MainWindow", "(Зона III H=0.5-0.8 м) - 2.25"))
        self.comboBox_ground_electrode_horizontal_climat_coeff.setItemText(4, _translate("MainWindow", "(Зона IV H=0.5-0.8 м) - 1.75"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Нормативное значение"))
        self.label_9.setText(_translate("MainWindow", "Нормируемое сопротивление растеканию тока в землю\n"
" (допустимое при данном грунте)"))
        self.label_12.setText(_translate("MainWindow", "Ом"))
        self.comboBox_permissible_resistance.setItemText(0, _translate("MainWindow", "Выбрать из списка значений"))
        self.comboBox_permissible_resistance.setItemText(1, _translate("MainWindow", "0.5"))
        self.comboBox_permissible_resistance.setItemText(2, _translate("MainWindow", "1"))
        self.comboBox_permissible_resistance.setItemText(3, _translate("MainWindow", "2"))
        self.comboBox_permissible_resistance.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_permissible_resistance.setItemText(5, _translate("MainWindow", "8"))
        self.comboBox_permissible_resistance.setItemText(6, _translate("MainWindow", "10"))
        self.comboBox_permissible_resistance.setItemText(7, _translate("MainWindow", "15"))
        self.comboBox_permissible_resistance.setItemText(8, _translate("MainWindow", "30"))
        self.comboBox_permissible_resistance.setItemText(9, _translate("MainWindow", "60"))
        self.label.setText(_translate("MainWindow", "Сопротивление естественного заземлителя"))
        self.label_2.setText(_translate("MainWindow", "Ом"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Исполнение заземляющего устройства"))
        self.label_135.setText(_translate("MainWindow", "Расположение вертикальных заземлителей"))
        self.label__a_div_l.setText(_translate("MainWindow", "Отношение расстояния между вертикальными электродами к длине электрода (a/l)"))
        self.label_137.setText(_translate("MainWindow", "м"))
        self.label_grounding_contour_width.setText(_translate("MainWindow", "Ширина контура заземления (B, только для контурного)"))
        self.comboBox_contoured.setItemText(0, _translate("MainWindow", "В ряд"))
        self.comboBox_contoured.setItemText(1, _translate("MainWindow", "По контуру"))
        self.label_134.setText(_translate("MainWindow", "Длина горизонтального заземлителя (A, длина контура заземления)"))
        self.label_138.setText(_translate("MainWindow", "м"))
        self.label_5.setText(_translate("MainWindow", "Количество вертикальных электродов"))
        self.label_8.setText(_translate("MainWindow", "шт."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_init_data), _translate("MainWindow", "Исходные данные"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Результаты расчета заземляющего устройства"))
        self.label_4.setText(_translate("MainWindow", "Ом"))
        self.label_n.setText(_translate("MainWindow", "-"))
        self.label_Ip0max_1ph_25.setText(_translate("MainWindow", "Уточненное количество вертикальных заземлителей с учетом соединительной полосы"))
        self.label_n_pr.setText(_translate("MainWindow", "-"))
        self.label_151.setText(_translate("MainWindow", "Расчетное удельное сопротивление грунта"))
        self.label_152.setText(_translate("MainWindow", "Ом·м"))
        self.label_155.setText(_translate("MainWindow", "шт."))
        self.label_R_v.setText(_translate("MainWindow", "-"))
        self.label_R_h.setText(_translate("MainWindow", "-"))
        self.label_R_vo.setText(_translate("MainWindow", "-"))
        self.label_t.setText(_translate("MainWindow", "-"))
        self.label_ro.setText(_translate("MainWindow", "-"))
        self.label_159.setText(_translate("MainWindow", "Ом"))
        self.label_133.setText(_translate("MainWindow", "Параметр"))
        self.label_153.setText(_translate("MainWindow", "Ом"))
        self.label_157.setText(_translate("MainWindow", "м"))
        self.label_L_h.setText(_translate("MainWindow", "-"))
        self.label_Ki_h.setText(_translate("MainWindow", "-"))
        self.label_160.setText(_translate("MainWindow", "шт."))
        self.label_139.setText(_translate("MainWindow", "Ед. изм"))
        self.label_140.setText(_translate("MainWindow", "Значение"))
        self.label_158.setText(_translate("MainWindow", "Ом"))
        self.label_154.setText(_translate("MainWindow", "м"))
        self.label_k_Lh_to_Lv.setText(_translate("MainWindow", "-"))
        self.label_a_div_l.setText(_translate("MainWindow", "-"))
        self.label_Ip0max_1ph_15.setText(_translate("MainWindow", "Расстояние от поверхности земли до середины заземлителя"))
        self.label_Ip0max_1ph_16.setText(_translate("MainWindow", "Сопротивление одного вертикального заземлителя"))
        self.label_Ip0max_1ph_17.setText(_translate("MainWindow", "Предварительное количество вертикальных заземлителей (без учета экранирования)"))
        self.label_Ip0max_1ph_18.setText(_translate("MainWindow", "Отношение расстояния между электродами к длине электрода"))
        self.label_Ip0max_1ph_21.setText(_translate("MainWindow", "Длина горизонтального заземлителя"))
        self.label_Ip0max_1ph_22.setText(_translate("MainWindow", "Коэффициент использования горизонтальных электродов"))
        self.label_Ip0max_1ph_23.setText(_translate("MainWindow", "Сопротивление горизонтального заземлителя"))
        self.label_Ip0max_1ph_24.setText(_translate("MainWindow", "Уточненное сопротивление вертикальных заземлителей"))
        self.label_Ip0max_1ph_26.setText(_translate("MainWindow", "Условие a/l>1 (a - расстояние между вертикальными электродами, м; l - длина электрода, м)"))
        self.label_7.setText(_translate("MainWindow", "Ом"))
        self.label_3.setText(_translate("MainWindow", "Необходимое сопротивление искусственного заземлителя \n"
"с учётом использования естественных заземлителей"))
        self.label_Rfull.setText(_translate("MainWindow", "-"))
        self.label_R_artificial.setText(_translate("MainWindow", "-"))
        self.label_6.setText(_translate("MainWindow", "Полное сопротивление растеканию заземляющего устройства"))
        self.label_Ip0max_1ph_19.setText(_translate("MainWindow", "Предварительный коэффициент использования вертикальных электродов"))
        self.label_Ki_v_pr.setText(_translate("MainWindow", "-"))
        self.label_Ip0max_1ph_39.setText(_translate("MainWindow", "Уточнённый коэффициент использования вертикальных электродов"))
        self.label_Ki_v.setText(_translate("MainWindow", "-"))
        self.label_20.setText(_translate("MainWindow", "Расстояние между вертикальными заземлителями"))
        self.label_h.setText(_translate("MainWindow", "-"))
        self.label_173.setText(_translate("MainWindow", "м"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_calc_results), _translate("MainWindow", "Результаты расчёта"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Результаты проверки заземляющего устройства"))
        self.label_Ip0max_1ph_50.setText(_translate("MainWindow", "Коэффициент использования вертикальных электродов"))
        self.label_176.setText(_translate("MainWindow", "Ом"))
        self.label_Ki_h_check.setText(_translate("MainWindow", "-"))
        self.label_a_div_l_check.setText(_translate("MainWindow", "-"))
        self.label_Ip0max_1ph_47.setText(_translate("MainWindow", "Полное сопротивление вертикальных заземлителей"))
        self.label_R_v_check.setText(_translate("MainWindow", "-"))
        self.label_k_Lh_to_Lv_check.setText(_translate("MainWindow", "-"))
        self.label_23.setText(_translate("MainWindow", "Необходимое сопротивление искусственного заземлителя \n"
"с учётом использования естественных заземлителей"))
        self.label_Ip0max_1ph_48.setText(_translate("MainWindow", "Условие a/l>1 (a - расстояние между вертикальными электродами, м; l - длина электрода, м)"))
        self.label_Ip0max_1ph_46.setText(_translate("MainWindow", "Сопротивление горизонтального заземлителя"))
        self.label_R_h_check.setText(_translate("MainWindow", "-"))
        self.label_179.setText(_translate("MainWindow", "м"))
        self.label_t_check.setText(_translate("MainWindow", "-"))
        self.label_22.setText(_translate("MainWindow", "Ом"))
        self.label_Ip0max_1ph_20.setText(_translate("MainWindow", "Расстояние от поверхности земли до середины заземлителя"))
        self.label_184.setText(_translate("MainWindow", "м"))
        self.label_Ip0max_1ph_43.setText(_translate("MainWindow", "Отношение расстояния между электродами к длине электрода"))
        self.label_Rfull_check.setText(_translate("MainWindow", "-"))
        self.label_156.setText(_translate("MainWindow", "Расчетное удельное сопротивление грунта"))
        self.label_Ip0max_1ph_44.setText(_translate("MainWindow", "Длина горизонтального заземлителя"))
        self.label_Ip0max_1ph_45.setText(_translate("MainWindow", "Коэффициент использования горизонтальных электродов"))
        self.label_R_artificial_check.setText(_translate("MainWindow", "-"))
        self.label_24.setText(_translate("MainWindow", "Полное сопротивление растеканию заземляющего устройства"))
        self.label_182.setText(_translate("MainWindow", "Значение"))
        self.label_R_vo_check.setText(_translate("MainWindow", "-"))
        self.label_181.setText(_translate("MainWindow", "Ед. изм"))
        self.label_Ip0max_1ph_41.setText(_translate("MainWindow", "Сопротивление одного вертикального заземлителя"))
        self.label_177.setText(_translate("MainWindow", "Параметр"))
        self.label_174.setText(_translate("MainWindow", "Ом·м"))
        self.label_ro_check.setText(_translate("MainWindow", "-"))
        self.label_21.setText(_translate("MainWindow", "Ом"))
        self.label_L_h_check.setText(_translate("MainWindow", "-"))
        self.label_178.setText(_translate("MainWindow", "Ом"))
        self.label_183.setText(_translate("MainWindow", "Ом"))
        self.label_Ki_v_check.setText(_translate("MainWindow", "-"))
        self.label_185.setText(_translate("MainWindow", "м"))
        self.label_h_check.setText(_translate("MainWindow", "-"))
        self.label_25.setText(_translate("MainWindow", "Расстояние между вертикальными заземлителями"))
        self.label_26.setText(_translate("MainWindow", "Удовлетворение нормативным требованиям"))
        self.label_result_check.setText(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_check_results), _translate("MainWindow", "Результаты проверки"))
        self.menu_File.setTitle(_translate("MainWindow", "&Файл"))
        self.menu_Calculation.setTitle(_translate("MainWindow", "Расчёт"))
        self.menu_Report.setTitle(_translate("MainWindow", "Отчёт"))
        self.menu_Help.setTitle(_translate("MainWindow", "Инструменты"))
        self.menu.setTitle(_translate("MainWindow", "Справка"))
        self.action_Calculate.setText(_translate("MainWindow", "Запустить расчёт"))
        self.action_db.setText(_translate("MainWindow", "База данных"))
        self.action_Open.setText(_translate("MainWindow", "Открыть"))
        self.action_Save.setText(_translate("MainWindow", "Сохранить"))
        self.action_Exit.setText(_translate("MainWindow", "В&ыход"))
        self.action_ODT.setText(_translate("MainWindow", "Сохранить отчёт как ODT"))
        self.action_About.setText(_translate("MainWindow", "О программе"))
        self.action_Qt.setText(_translate("MainWindow", "Версия Qt"))
        self.action_clean_form.setText(_translate("MainWindow", "Очистить форму"))
        self.action_DOCX.setText(_translate("MainWindow", "Сохранить отчёт как DOCX"))
        self.action_minimize_to_tray.setText(_translate("MainWindow", "Сворачивать в трей"))

